//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGNotifier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyGNotifier_Local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyGNotifier_Local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyGNotifier.MyGNotifier_Local", typeof(MyGNotifier_Local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALVA IMPOSTAZIONI.
        /// </summary>
        internal static string btnSalvaImpostazioni {
            get {
                return ResourceManager.GetString("btnSalvaImpostazioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONITORA DURATA CONTROLLI CASELLA DI POSTA NEL LOG.
        /// </summary>
        internal static string chkCHECK_MONITOR {
            get {
                return ResourceManager.GetString("chkCHECK_MONITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APRI GMAIL AL DOPPIO CLICK SULL&apos;ICONA.
        /// </summary>
        internal static string chkDOPPPIO_CLICK {
            get {
                return ResourceManager.GetString("chkDOPPPIO_CLICK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHIEDI PASSWORD DI SISTEMA AD OGNI AVVIO.
        /// </summary>
        internal static string chkMainPwd {
            get {
                return ResourceManager.GetString("chkMainPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOSTRA NOTIFICA ERRORE IN AUTOMATICO.
        /// </summary>
        internal static string chkMOSTRA_NOTIFICA_ERRORE {
            get {
                return ResourceManager.GetString("chkMOSTRA_NOTIFICA_ERRORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOSTRA NOTIFICHE MESSAGGI IN AUTOMATICO.
        /// </summary>
        internal static string chkMOSTRA_NOTIFICHE_MESSAGGI_AUTO {
            get {
                return ResourceManager.GetString("chkMOSTRA_NOTIFICHE_MESSAGGI_AUTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTILIZZA NOTIFICHE STILE OUTLOOK.
        /// </summary>
        internal static string chkRAD_NOTIFIER {
            get {
                return ResourceManager.GetString("chkRAD_NOTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG ERRORI MESSAGGI IMAP.
        /// </summary>
        internal static string grLogErroriMessaggiImap {
            get {
                return ResourceManager.GetString("grLogErroriMessaggiImap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG SCAN MESSAGGI IMAP.
        /// </summary>
        internal static string grLogScanMessaggiImap {
            get {
                return ResourceManager.GetString("grLogScanMessaggiImap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELTA ALTEZZA NOTIFICA (pixel).
        /// </summary>
        internal static string lblDeltaAltezzaNotifica {
            get {
                return ResourceManager.GetString("lblDeltaAltezzaNotifica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREQUENZA AGGIORNAMENTO (millisecondi).
        /// </summary>
        internal static string lblFrequenzaAggiornamento {
            get {
                return ResourceManager.GetString("lblFrequenzaAggiornamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD DI SISTEMA.
        /// </summary>
        internal static string lblPasswordSistema {
            get {
                return ResourceManager.GetString("lblPasswordSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTA IMAP.
        /// </summary>
        internal static string lblPortImap {
            get {
                return ResourceManager.GetString("lblPortImap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER IMAP.
        /// </summary>
        internal static string lblServerImap {
            get {
                return ResourceManager.GetString("lblServerImap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPOSTAZIONI DI CONNESSIONE ASSENTI! PROCEDERE ALLA MEMORIZZAZIONE!.
        /// </summary>
        internal static string lblSettingStatusNO {
            get {
                return ResourceManager.GetString("lblSettingStatusNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPOSTAZIONI DI CONNESSIONE OK!.
        /// </summary>
        internal static string lblSettingStatusOK {
            get {
                return ResourceManager.GetString("lblSettingStatusOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMA DI DEFAULT NOTIFICA STILE OUTLOOK.
        /// </summary>
        internal static string lblTemaDefaultStileOutlook {
            get {
                return ResourceManager.GetString("lblTemaDefaultStileOutlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GESTIONE IMPOSTAZIONI.
        /// </summary>
        internal static string TAB_IMPOSTAZIONI {
            get {
                return ResourceManager.GetString("TAB_IMPOSTAZIONI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPOSTAZIONI DI CONNESSIONE.
        /// </summary>
        internal static string TAB_IMPOSTAZIONI_CONNESSIONE {
            get {
                return ResourceManager.GetString("TAB_IMPOSTAZIONI_CONNESSIONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPOSTAZIONI DI SISTEMA.
        /// </summary>
        internal static string TAB_IMPOSTAZIONI_SISTEMA {
            get {
                return ResourceManager.GetString("TAB_IMPOSTAZIONI_SISTEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG APPLICAZIONE.
        /// </summary>
        internal static string TAB_LOG {
            get {
                return ResourceManager.GetString("TAB_LOG", resourceCulture);
            }
        }
    }
}
