//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGNotifier.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IMAP_SERVER {
            get {
                return ((string)(this["IMAP_SERVER"]));
            }
            set {
                this["IMAP_SERVER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IMAP_PORT {
            get {
                return ((int)(this["IMAP_PORT"]));
            }
            set {
                this["IMAP_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IMAP_USERNAME {
            get {
                return ((string)(this["IMAP_USERNAME"]));
            }
            set {
                this["IMAP_USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IMAP_PASSWORD {
            get {
                return ((string)(this["IMAP_PASSWORD"]));
            }
            set {
                this["IMAP_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MAIN_PASSWORD {
            get {
                return ((string)(this["MAIN_PASSWORD"]));
            }
            set {
                this["MAIN_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MAIN_PASS_SHOW {
            get {
                return ((bool)(this["MAIN_PASS_SHOW"]));
            }
            set {
                this["MAIN_PASS_SHOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_DOUBLE_CLICK_GMAIL {
            get {
                return ((bool)(this["MAIN_DOUBLE_CLICK_GMAIL"]));
            }
            set {
                this["MAIN_DOUBLE_CLICK_GMAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_AUTO_NOTIFY_ERROR {
            get {
                return ((bool)(this["MAIN_AUTO_NOTIFY_ERROR"]));
            }
            set {
                this["MAIN_AUTO_NOTIFY_ERROR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MAIN_AUTO_NOTIFY_MSGS {
            get {
                return ((bool)(this["MAIN_AUTO_NOTIFY_MSGS"]));
            }
            set {
                this["MAIN_AUTO_NOTIFY_MSGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int MAIN_TIMER_REFRESH {
            get {
                return ((int)(this["MAIN_TIMER_REFRESH"]));
            }
            set {
                this["MAIN_TIMER_REFRESH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_KEEP_CONNECTION_ALIVE {
            get {
                return ((bool)(this["MAIN_KEEP_CONNECTION_ALIVE"]));
            }
            set {
                this["MAIN_KEEP_CONNECTION_ALIVE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MAIN_CHECK_MONITOR {
            get {
                return ((bool)(this["MAIN_CHECK_MONITOR"]));
            }
            set {
                this["MAIN_CHECK_MONITOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MAIN_RAD_NOTIFIER {
            get {
                return ((bool)(this["MAIN_RAD_NOTIFIER"]));
            }
            set {
                this["MAIN_RAD_NOTIFIER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MAIN_RAD_THEME {
            get {
                return ((string)(this["MAIN_RAD_THEME"]));
            }
            set {
                this["MAIN_RAD_THEME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int MAIN_NOTIFIER_HEIGHT {
            get {
                return ((int)(this["MAIN_NOTIFIER_HEIGHT"]));
            }
            set {
                this["MAIN_NOTIFIER_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MAIN_CLEAN_LOGS {
            get {
                return ((bool)(this["MAIN_CLEAN_LOGS"]));
            }
            set {
                this["MAIN_CLEAN_LOGS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public int MAIN_CLEAN_LOGS_INTERVAL {
            get {
                return ((int)(this["MAIN_CLEAN_LOGS_INTERVAL"]));
            }
            set {
                this["MAIN_CLEAN_LOGS_INTERVAL"] = value;
            }
        }
    }
}
